import { IInfodashConfiguration, IUser } from  "./interfaces";

export const Config: IInfodashConfiguration = {
    "LogoImageUrl": "https://pbs.twimg.com/profile_images/1267859779424096256/WZnjai6Z_400x400.png",
    "HideSharePointGlobalNavigationAppBar": true,
    "HideSharePointOOTBNavigation": true,
    "TopView": "compact",
    "MyAppsList": "Firm Apps",
    "MyAppsSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "MegaMenuList": "MegaMenu Links",
    "FooterList": "Footer Links",
    "FooterSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "FooterView": "default",
    "PrivacyText": "",
    "LogoClickUrl": "/sites/infodashcore",
    "GlobalCssUrl": "https://infodashdemo.sharepoint.com/sites/InfodashCore/InfodashAssets/css/overrides.css",
    "DisableCssCaching": false,
    "HideSharePointSuiteBar": true,
    "EnableBreadcrumbs": false,
    "NavigationBackgroundImage": "",
    "NavigationTheme": "default",
    "NavigationBackgroundColor": "",
    "NavigationTextColor": "",
    "LinkedInUrl": "",
    "TwitterUrl": "",
    "YouTubeUrl": "",
    "FacebookUrl": "",
    "ContactEmail": "",
    "EnableActiveResults": true,
    "DefaultSearchResultsPageUrl": "https://infodashdemo.sharepoint.com/sites/infodashcore/sitepages/results.aspx",
    "ActiveSearchMinimumCharacterLength": "2",
    "SearchPlaceholderText": "Search content, people, matters and documents...",
    "GoogleMapAPIKey": "",
    "GoogleTrackingJSUrl": "",
    "InfodashAppRegistrationClientId": "",
    "WeatherCacheSite": "",
    "WeatherCacheList": "",
    "WeatherCacheTime": "",
    "OpenWeatherAPIKey": "",
    "SavedConfigSite": "",
    "SavedConfigList": "",
    "LinkCatalogList": "Link Catalog",
    "LinkCatalogSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "EventRegistrationSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "EventRegistrationList": "Event Registrations",
    "ProfileBannerSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "ProfileBannerList": "",
    "PersonalProfileBannerSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "PersonalProfileBannerList": "BannerImages",
    "BreadcrumbsSite": "",
    "BreadcrumbsList": "",
    "DynamicComponentManifest": "https://infodashdemo.sharepoint.com/sites/InfodashCore/InfodashAssets/infodash.component.manifest.json",
    "TrackingServiceAppName": "Infodash",
    "TrackingServiceInstrumentationKey": "e7c14af5-7e03-4cc1-a73c-6b49ed4bb9c8",
    "TrackingServiceHashUsername": true,
    "TrackingServiceAPIReadTelemetryKey": "",
    "TrackingServiceApplicationID": "",
    "UserProfilePageUrl": "/sites/InfodashCore/SitePages/Profile.aspx",
    "ClientDetailsPageUrl": "/sites/InfodashCore/SitePages/Client.aspx",
    "MatterDetailsPageUrl": "/sites/InfodashCore/SitePages/Matter.aspx",
    "EventViewerPageUrl": "/sites/InfodashCore/SitePages/Event.aspx",
    "DefaultAvatarImageUrl": "https://infodashreleases.blob.core.windows.net/images/avatar.png",
    "DefaultEventImageUrl": "https://i.pinimg.com/originals/87/21/98/872198c2f62aa608f6d657b61c5e65b6.jpg",
    "DefaultNewsImageUrl": "/sites/infodash/SitePages/LegalZoomApprovalAZ/9367-Free-vector-graphic--Mesh--Background--Triangles---Free----.png",
    "DefaultCarouselImageUrl": "https://morethandigital.info/wp-content/uploads/2018/07/12-websites-for-royalty-free-stock-photos-with-CC0-and-free-of-charge.jpeg",
    "DefaultAppImageUrl": "https://infodashdemo.sharepoint.com/sites/InfodashCore/InfodashAssets/images/process.png",
    "DefaultImageCardUrl": "",
    "DefaultOfficeBanner": "",
    "AdminPage": "/sites/infodash/SitePages/Infodash-Admin.aspx",
    "AvatarImageStyle": "circle",
    "Theme": {
        "themePrimary": "#034a84",
        "themeLighterAlt": "#f0f6fa",
        "themeLighter": "#c7dbeb",
        "themeLight": "#9abdda",
        "themeTertiary": "#4b86b6",
        "themeSecondary": "#145a93",
        "themeDarkAlt": "#024377",
        "themeDark": "#023865",
        "themeDarker": "#012a4a",
        "neutralLighterAlt": "#faf9f8",
        "neutralLighter": "#f3f2f1",
        "neutralLight": "#edebe9",
        "neutralQuaternaryAlt": "#e1dfdd",
        "neutralQuaternary": "#d0d0d0",
        "neutralTertiaryAlt": "#c8c6c4",
        "neutralTertiary": "#a19f9d",
        "neutralSecondary": "#605e5c",
        "neutralPrimaryAlt": "#3b3a39",
        "neutralPrimary": "#323130",
        "neutralDark": "#201f1e",
        "black": "#000000",
        "white": "#ffffff"
    },
    "FavIconUrl": "https://media.legaltechnologyhub.com/1678460615240_ba3cf1f395.jpeg",
    "ChartColor1": "",
    "ChartColor2": "",
    "ChartColor3": "",
    "ChartColor4": "",
    "ChartColor5": "",
    "ChartColor6": "",
    "ChartColor7": "",
    "ChartColor8": "",
    "ChartColor9": "",
    "ChartColor10": "",
    "DisplayNameFormat": "FirstNameLastName",
    "AllowProfileUpdates": false,
    "AllowPersonalizedBanner": false,
    "AllowUserDefinedPersonalizedBanner": false,
    "ActiveSearchResultsOrientation": "vertical",
    "EnableMyAppsPanel": true,
    "MyAppsAdminEmail": "",
    "PublicWebsite": "",
    "HideSharePointHubSiteNavigation": true,
    "MegaMenuSite": "https://infodashdemo.sharepoint.com/sites/InfodashCore",
    "BreadcrumbsSiteId": null,
    "DefaultPageHeaderUrl": "",
    "TemperatureUnit": "f",
    "MeasurementSystem": "imperial",
    "EventRegistrationSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "LinkCatalogSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "UserSettingsSiteId": null,
    "WeatherCacheSiteId": null,
    "ProfileBannerSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "CodeSnippetSiteId": null,
    "FooterSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "MyAppsSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "DisableTeamsIntegrationControls": false,
    "NoNotificationsMessage": "There are no new messages.",
    "NotificationDeleteThreshold": "1",
    "EnableNotifications": true,
    "NotificationCenterPageUrl": "/sites/infodash/SitePages/Notifications.aspx",
    "FixedWidthLayout": true,
    "PersonalProfileBannerSiteId": "infodashdemo.sharepoint.com,ac571bb4-5115-42ed-b5c8-1183f7065263,a547d047-cb7d-4ecc-90bb-66553a60cd4d",
    "Languages": [
        {
            "name": "English",
            "abbreviation": "en",
            "icon": "us",
            "enabled": true
        },
        {
            "name": "French",
            "abbreviation": "fr",
            "icon": "ca",
            "enabled": false
        }
    ],
    "NotificationCacheTime": "1",
    "AppInsightsAppId": "3694f3d8-d895-435d-a756-88e88b8d5119",
    "DisableAdvancedClientTelemetry": false,
    "NavigationFlyoutStyle": "megaMenuXL",
    "ContentTypeHubMigration": 1,
    "UserSettingsSite": "",
    "UserSettingsList": "",
    "CustomProfileBannerSite": null,
    "CustomProfileBannerSiteId": null,
    "CustomProfileBannerList": null,
    "FixedWidth": true,
    "EnableSidebar": false,
    "NetDocsRequestedScope": "full",
    "NetDocsRegion": "vault.netvoyage.com",
    "ConfigName": "fenwick",
    "LinkCatalog": {
        "Energy": "https://infodashdemo.sharepoint.com/sites/InfodashCore/Department/KnowledgeManagement/Sitepages/Home.aspx",
        "Management Committee": "https://infodashdemo.sharepoint.com/sites/InfodashCore/Committee/Management",
        "Paralegal": "https://infodashdemo.sharepoint.com/sites/InfodashCore/SitePages/People.aspx?k=Paralegal",
        "Charlotte": "https://infodashdemo.sharepoint.com/sites/InfodashCore/Office/Charlotte/SitePages/Home.aspx"
    }
}

export const User: IUser = {
    "AccountName": "i:0#.f|membership|admin@infodashdemo.onmicrosoft.com",
    "Initials": "AD",
    "DirectReports": [],
    "DisplayName": "Infodash Admin",
    "Email": "admin@infodashdemo.onmicrosoft.com",
    "ExtendedManagers": [],
    "ExtendedReports": [],
    "IsFollowed": false,
    "LatestPost": null,
    "Peers": [],
    "PersonalSiteHostUrl": "https://infodashdemo-my.sharepoint.com:443/",
    "PersonalUrl": "https://infodashdemo-my.sharepoint.com/personal/admin_infodashdemo_onmicrosoft_com/",
    "PictureUrl": "https://infodashdemo-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/444ec703-365f-4e24-b1a7-445c7ba65551_MThumb.jpg?t=63866679423",
    "Title": "Infodash Admin",
    "UserUrl": "https://infodashdemo-my.sharepoint.com:443/Person.aspx?accountname=i%3A0%23%2Ef%7Cmembership%7Cadmin%40infodashdemo%2Eonmicrosoft%2Ecom",
    "UserProfile_GUID": "72942d74-e73b-45e7-b7be-79ec8c1e3f1a",
    "SID": "i:0h.f|membership|1003200190ce6c64@live.com",
    "ADGuid": "System.Byte[]",
    "FirstName": "Infodash",
    "SPS-PhoneticFirstName": "",
    "LastName": "Admin",
    "SPS-PhoneticLastName": "",
    "PreferredName": "Infodash Admin",
    "SPS-PhoneticDisplayName": "",
    "WorkPhone": "(888) 999-7777",
    "Department": "Information Technology",
    "SPS-Department": "Information Technology",
    "Manager": "",
    "AboutMe": ["I enjoy building solutions with Infodash!"],
    "PersonalSpace": "/personal/admin_infodashdemo_onmicrosoft_com/",
    "PictureURL": "https://infodashdemo-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/444ec703-365f-4e24-b1a7-445c7ba65551_MThumb.jpg",
    "UserName": "admin@infodashdemo.onmicrosoft.com",
    "QuickLinks": "",
    "WebSite": "",
    "PublicSiteRedirect": "",
    "SPS-JobTitle": "Infodash Admin",
    "SPS-DataSource": "",
    "SPS-MemberOf": "",
    "SPS-Dotted-line": "",
    "SPS-Peers": "",
    "SPS-Responsibility": "SharePoint|SPFx",
    "SPS-SipAddress": "admin@infodashdemo.onmicrosoft.com",
    "SPS-MySiteUpgrade": "",
    "SPS-DontSuggestList": "",
    "SPS-ProxyAddresses": "",
    "SPS-HireDate": "6/5/2021 12:00:00 AM",
    "SPS-DisplayOrder": "",
    "SPS-ClaimID": "admin@infodashdemo.onmicrosoft.com",
    "SPS-ClaimProviderID": "membership",
    "SPS-LastColleagueAdded": "",
    "SPS-OWAUrl": "",
    "SPS-ResourceSID": "",
    "SPS-ResourceAccountName": "",
    "SPS-MasterAccountName": "",
    "SPS-UserPrincipalName": "admin@infodashdemo.onmicrosoft.com",
    "SPS-O15FirstRunExperience": "",
    "SPS-PersonalSiteInstantiationState": "2",
    "SPS-DistinguishedName": "CN=444ec703-365f-4e24-b1a7-445c7ba65551,OU=f9c5f38c-c094-475e-89a7-4b3307cfee12,OU=Tenants,OU=MSOnline,DC=SPODS192766,DC=msft,DC=net",
    "SPS-SourceObjectDN": "",
    "SPS-LastKeywordAdded": "2/10/2025 12:00:00 AM",
    "SPS-ClaimProviderType": "Forms",
    "SPS-SavedAccountName": "i:0#.f|membership|admin@infodashdemo.onmicrosoft.com",
    "SPS-SavedSID": "System.Byte[]",
    "SPS-ObjectExists": "",
    "SPS-PersonalSiteCapabilities": "36",
    "SPS-PersonalSiteFirstCreationTime": "10/1/2021 3:05:05 PM",
    "SPS-PersonalSiteLastCreationTime": "10/1/2021 3:05:05 PM",
    "SPS-PersonalSiteNumberOfRetries": "1",
    "SPS-PersonalSiteFirstCreationError": "",
    "SPS-FeedIdentifier": "",
    "WorkEmail": "admin@infodashdemo.onmicrosoft.com",
    "CellPhone": "(888) 999-7777",
    "Fax": "",
    "HomePhone": "",
    "Office": "New York",
    "SPS-Location": "New York",
    "Assistant": "",
    "SPS-PastProjects": "",
    "SPS-Skills": "",
    "SPS-School": "",
    "SPS-Birthday": "8/9/2024 12:00:00 AM",
    "SPS-StatusNotes": "",
    "SPS-Interests": "",
    "SPS-HashTags": "",
    "SPS-EmailOptin": "0",
    "SPS-PrivacyPeople": "True",
    "SPS-PrivacyActivity": "4095",
    "SPS-PictureTimestamp": "63866679423",
    "SPS-PicturePlaceholderState": "0",
    "SPS-PictureExchangeSyncState": "1",
    "SPS-MUILanguages": "en-US",
    "SPS-ContentLanguages": "ui-ui",
    "SPS-TimeZone": "",
    "SPS-RegionalSettings-FollowWeb": "True",
    "SPS-Locale": "",
    "SPS-CalendarType": "",
    "SPS-AltCalendarType": "",
    "SPS-AdjustHijriDays": "",
    "SPS-ShowWeeks": "False",
    "SPS-WorkDays": "",
    "SPS-WorkDayStartHour": "",
    "SPS-WorkDayEndHour": "",
    "SPS-Time24": "False",
    "SPS-FirstDayOfWeek": "",
    "SPS-FirstWeekOfYear": "",
    "SPS-RegionalSettings-Initialized": "True",
    "OfficeGraphEnabled": "",
    "SPS-UserType": "0",
    "SPS-HideFromAddressLists": "False",
    "SPS-RecipientTypeDetails": "",
    "DelveFlags": "",
    "PulseMRUPeople": "",
    "AadId": "444ec703-365f-4e24-b1a7-445c7ba65551",
    "msOnline-ObjectId": "444ec703-365f-4e24-b1a7-445c7ba65551",
    "SPS-PointPublishingUrl": "",
    "SPS-TenantInstanceId": "",
    "SPS-SharePointHomeExperienceState": "18352161",
    "SPS-RefreshToken": "",
    "SPS-MultiGeoFlags": "",
    "PreferredDataLocation": ""
} 